# Configuration file for TravisCI

language: generic

# Only build pushes to the master branch and tags. This avoids the double
# builds than happen when working on a branch instead of a fork.
branches:
  only:
    - master

install:
  - sudo apt-get install rpmlint

script:
  - rpmlint dcw-gmt.spec
  - rpmlint gshhg-gmt.spec
  - rpmlint gmt.spec
